# Generated by Django 4.2.5 on 2023-10-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtechnologies',
            name='profile',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cvuserprofile'),
        ),
        migrations.AddField(
            model_name='cvtechnologies',
            name='technology_type',
            field=models.CharField(choices=[('PROG_LANG', 'Programming language'), ('FWRK_LIB', 'Framework/Librarie'), ('FORMAT', 'Format'), ('DB', 'Database'), ('OS', 'Operating System'), ('DEV_TOOL', 'Development tool'), ('PROTOCOL', 'Protocol'), ('OTHER', 'Other')], default='FORMAT', max_length=12),
            preserve_default=False,
        ),
    ]
