# Generated by Django 4.2.5 on 2023-10-02 03:29

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cvtechnologies_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtechnologies',
            name='technology_type',
            field=models.CharField(choices=[('PROG_LANG', 'Programming language'), ('FWRK_LIB', 'Framework/Librarie'), ('FORMAT', 'Format'), ('DB', 'Database'), ('OS', 'Operating System'), ('DEV_TOOL', 'Development tool'), ('PROTOCOL', 'Protocol'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='cvtechnologies',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('technology_type'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('technology_type'))), (models.Value(1), models.Value(10)))), name='cv_cvtechnologies_technology_type_range'),
        ),
    ]
