# Generated by Django 4.2.5 on 2023-10-02 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cvtechnologies_technology_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtechnologies',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cvuserprofile'),
        ),
    ]
