# Generated by Django 4.2.5 on 2023-10-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_cvtechnologies_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtechnologies',
            name='technology_type',
            field=models.CharField(choices=[('PROG_LANG', 'Programming language'), ('FWRK_LIB', 'Framework/Library'), ('FORMAT', 'Format'), ('DB', 'Database'), ('OS', 'Operating System'), ('DEV_TOOL', 'Development tool'), ('PROTOCOL', 'Protocol'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
