# Generated by Django 4.2.5 on 2023-10-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_cvtechnologies_technology_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvprojecttechnology',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cvtechnologies'),
        ),
    ]
