# Generated by Django 4.2.5 on 2023-10-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_cvprojecttechnology_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvprojecttechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cvtechnologies'),
        ),
    ]
