# Generated by Django 4.2.5 on 2023-10-12 12:39

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_cvprojecttechnology_technology'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cvproject',
            name='cv_cvproject_description_range',
        ),
        migrations.AlterField(
            model_name='cvproject',
            name='description',
            field=models.TextField(max_length=8192),
        ),
        migrations.AddConstraint(
            model_name='cvproject',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('description'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('description'))), (models.Value(1), models.Value(8192)))), name='cv_cvproject_description_range'),
        ),
    ]
