# Generated by Django 4.2.5 on 2023-10-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_remove_cvproject_cv_cvproject_description_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvproject',
            name='title',
            field=models.TextField(default='fff', max_length=248),
            preserve_default=False,
        ),
    ]
