# Generated by Django 4.2.5 on 2023-10-12 12:57

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_cvproject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvproject',
            name='title',
            field=models.CharField(max_length=248),
        ),
        migrations.AddConstraint(
            model_name='cvproject',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('title'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('title'))), (models.Value(1), models.Value(248)))), name='cv_cvproject_title_range'),
        ),
    ]
