# Generated by Django 4.2.5 on 2023-10-13 15:28

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_alter_cvproject_prerequisite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cvproject',
            name='cv_cvproject_prerequisite_range',
        ),
        migrations.RemoveConstraint(
            model_name='cvproject',
            name='cv_cvproject_result_range',
        ),
        migrations.AddConstraint(
            model_name='cvproject',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('prerequisite'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('prerequisite'))), (models.Value(0), models.Value(248)))), name='cv_cvproject_prerequisite_range'),
        ),
        migrations.AddConstraint(
            model_name='cvproject',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('result'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('result'))), (models.Value(0), models.Value(248)))), name='cv_cvproject_result_range'),
        ),
    ]
