# Generated by Django 4.2.5 on 2023-10-16 06:53

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_remove_cvproject_cv_cvproject_prerequisite_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvworkplaceresponsibility',
            name='responsibility',
            field=models.TextField(max_length=1024),
        ),
        migrations.AddConstraint(
            model_name='cvworkplaceresponsibility',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('responsibility'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('responsibility'))), (models.Value(1), models.Value(1024)))), name='cv_cvworkplaceresponsibility_responsibility_range'),
        ),
    ]
