# Generated by Django 4.2.5 on 2023-10-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_alter_cvworkplaceresponsibility_responsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvuserprofile',
            name='cover_letter',
            field=models.TextField(blank=True, default='', max_length=8192),
        ),
        migrations.AddField(
            model_name='cvuserprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=248),
        ),
        migrations.AddField(
            model_name='cvuserprofile',
            name='soft_skill',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='cvuserprofile',
            name='summary_qualification',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
