# Generated by Django 4.2.5 on 2023-10-17 13:49

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_cvuserprofile_cv_cvuserprofile_soft_skill_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cvuserprofile',
            name='cv_cvuserprofile_soft_skill_range',
        ),
        migrations.RemoveConstraint(
            model_name='cvuserprofile',
            name='cv_cvuserprofile_summary_qualification_range',
        ),
        migrations.RemoveConstraint(
            model_name='cvuserprofile',
            name='cv_cvuserprofile_position_range',
        ),
        migrations.RemoveConstraint(
            model_name='cvuserprofile',
            name='cv_cvuserprofile_cover_letter_range',
        ),
        migrations.AlterField(
            model_name='cvuserprofile',
            name='cover_letter',
            field=models.TextField(blank=True, default=None, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='cvuserprofile',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='cvuserprofile',
            name='soft_skill',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cvuserprofile',
            name='summary_qualification',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AddConstraint(
            model_name='cvuserprofile',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('soft_skill'))), (models.Value(0), models.Value(1024)))), name='cv_cvuserprofile_soft_skill_range'),
        ),
        migrations.AddConstraint(
            model_name='cvuserprofile',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('summary_qualification'))), (models.Value(0), models.Value(2048)))), name='cv_cvuserprofile_summary_qualification_range'),
        ),
        migrations.AddConstraint(
            model_name='cvuserprofile',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('position'))), (models.Value(0), models.Value(248)))), name='cv_cvuserprofile_position_range'),
        ),
        migrations.AddConstraint(
            model_name='cvuserprofile',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('cover_letter'))), (models.Value(0), models.Value(8192)))), name='cv_cvuserprofile_cover_letter_range'),
        ),
    ]
