# Generated by Django 4.2.5 on 2023-10-18 02:30

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_remove_cvuserprofile_cv_cvuserprofile_soft_skill_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cvtechnologies',
            name='cv_cvtechnologies_technology_range',
        ),
        migrations.AlterField(
            model_name='cvtechnologies',
            name='technology',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cvtechnologies',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('technology'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('technology'))), (models.Value(1), models.Value(48)))), name='cv_cvtechnologies_technology_range'),
        ),
    ]
