# Generated by Django 4.2.5 on 2023-10-24 19:45

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_remove_cvtechnologies_cv_cvtechnologies_technology_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cvprojecttechnology',
            name='cv_cvprojecttechnology_notes_range',
        ),
        migrations.AlterField(
            model_name='cvprojecttechnology',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=248, null=True),
        ),
        migrations.AddConstraint(
            model_name='cvprojecttechnology',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('notes'))), (models.Value(0), models.Value(248)))), name='cv_cvprojecttechnology_notes_range'),
        ),
    ]
