# Generated by Django 4.2.5 on 2023-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_remove_cvprojecttechnology_cv_cvprojecttechnology_notes_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cvtechnologies',
            name='cv_cvtechnologies_technology_type_range',
        ),
        migrations.RemoveConstraint(
            model_name='cvtechnologies',
            name='cv_cvtechnologies_technology_range',
        ),
        migrations.AlterField(
            model_name='cvtechnologies',
            name='technology',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterUniqueTogether(
            name='cvtechnologies',
            unique_together={('technology', 'profile')},
        ),
    ]
