# Generated by Django 4.2.5 on 2023-10-26 05:55

import apps.cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_remove_cvtechnologies_cv_cvtechnologies_technology_type_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvuserprofile',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.cv.models.profile_photo_upload_to),
        ),
    ]
