# Generated by Django 4.2.5 on 2023-10-26 07:05

from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_alter_cvuserprofile_photo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cvtechnologies',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('technology'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('technology'))), (models.Value(1), models.Value(48)))), name='cv_cvtechnologies_technology_range'),
        ),
        migrations.AddConstraint(
            model_name='cvtechnologies',
            constraint=models.CheckConstraint(check=models.Q(django.db.models.lookups.IsNull(models.F('technology_type'), False), django.db.models.lookups.Range(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('technology_type'))), (models.Value(1), models.Value(10)))), name='cv_cvtechnologies_technology_type_range'),
        ),
    ]
